### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by xychix** [ah8r/csrf#2]
Hey Adrian, good plugin, however I see CSRF tokens like __RequestVerificationToken_UYVUIIUG675fI

Unfortunately I'm no java devver so I won't be able to write a patch myself, but would it be possible to include a wildcard in the token names that are 'recognized'?

Regards,
xychix

**Comment by ah8r** [comment]
I'm working on this currently. Hopefully I will be able to get an update out soon that will allow both wildcard and regex token name matches.

**Comment by starbuck3000** [comment]
+1

**Comment by ah8r** [comment]
This has (finally) been added in commit 72c9a378439fdb19f364d3a879db6463fea4121c. You can now add CSRF tokens to match as either literal strings (how it was before) or regular expressions. Note that regular expressions are not the same as wildcards, but are more powerful. For most purposes, you can use wildcard matching in regular expressions by putting .* rather than *

For example, to match `__RequestVerificationToken_UYVUIIUG675fI` and similar tokens, you could create the following regular expression: `__RequestVerificationToken_[A-Za-z0-9]+`

Or simply: `__RequestVerificationToken_.*`
