### ISSUE TITLE
Feature request: separate 'URL query' from 'HTTP body' in passive scan rules

### ISSUE THREAD

**Issue by starbuck3000** [ah8r/csrf#5]
This would be very helpful for websites that expose parameterized urls for static resources.

**Comment by ah8r** [comment]
If I'm understanding you correctly, you want:

1) Separate checkboxes for "URL Query" and "HTTP Body" rather than both being the same checkbox, so you can disable URL Query checks but keep HTTP Body checks enabled (for example).

2) Separate issues for missing tokens in URL Query / HTTP Body locations.

Is that correct?

**Comment by ah8r** [comment]
Closing due to lack of comment.
